//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID_admin { get; set; }
        public string Name_admin { get; set; }
        public string Surname_admin { get; set; }
        public string Telephone_admin { get; set; }
        public string mail_admin { get; set; }
    
        public virtual Staffing Staffing { get; set; }
    }
}
