//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_app
    {
        public int ID_business_app { get; set; }
        public string Name_business_app { get; set; }
        public decimal Price_business_app { get; set; }
    
        public virtual Package_services Package_services { get; set; }
    }
}
