//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_services
    {
        public int ID_package_services { get; set; }
        public string Name_services { get; set; }
        public string Name_business_app { get; set; }
    
        public virtual Business_app Business_app { get; set; }
        public virtual Services Services { get; set; }
    }
}
