//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ID_services { get; set; }
        public string Name_services { get; set; }
        public decimal Price_services { get; set; }
        public Nullable<bool> Popular_services { get; set; }
    
        public virtual Package_services Package_services { get; set; }
    }
}
