//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID_staff { get; set; }
        public string Name_staff { get; set; }
        public string Surname_staff { get; set; }
        public string Job_title_staff { get; set; }
    
        public virtual Staffing Staffing { get; set; }
    }
}
