//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAPP.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffing
    {
        public int ID_Staffing { get; set; }
        public string Name_admin { get; set; }
        public string Name_staff { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
